// Nigerian banks with their Paystack bank codes (used for account resolution
// and subaccount creation).
export const NIGERIAN_BANKS: { name: string; code: string }[] = [
  { name: "GTBank", code: "058" },
  { name: "Access Bank", code: "044" },
  { name: "Zenith Bank", code: "057" },
  { name: "First Bank", code: "011" },
  { name: "UBA", code: "033" },
  { name: "Stanbic IBTC", code: "221" },
  { name: "Fidelity Bank", code: "070" },
  { name: "Sterling Bank", code: "232" },
  { name: "Wema Bank", code: "035" },
  { name: "Polaris Bank", code: "076" },
  { name: "Union Bank", code: "032" },
  { name: "Keystone Bank", code: "082" },
  { name: "Ecobank", code: "050" },
  { name: "Heritage Bank", code: "030" },
  { name: "Jaiz Bank", code: "301" },
  { name: "Providus Bank", code: "101" },
  { name: "Titan Bank", code: "102" },
  { name: "SunTrust Bank", code: "100" },
  { name: "Signature Bank", code: "106" },
  { name: "Kuda Bank", code: "50211" },
  { name: "Opay", code: "999992" },
  { name: "Palmpay", code: "999991" },
  { name: "Moniepoint", code: "50515" },
  { name: "VFD Bank", code: "566" },
  { name: "Carbon", code: "565" },
];
