// Stock photo per event/circle category — fallback art for cards that have
// no uploaded cover, so nothing renders as a flat gradient or letter tile.
// Every photo shows a GROUP of people (3+), because the whole product is
// about linking up with others — a solo or empty-room shot sells the wrong
// idea. Files live in public/venues and public/circles.
const PHOTOS: Record<string, string> = {
  "Family Hangout": "/venues/parks.jpg",
  "Friend Reunion": "/circles/party.jpg",
  Picnic: "/venues/parks.jpg",
  "Book Club": "/circles/bookclub.jpg",
  "Game Night": "/circles/gamenight.jpg",
  "Board Games": "/circles/gamenight.jpg",
  Dinner: "/venues/restaurants.jpg",
  "Food Festival": "/venues/restaurants-2.jpg",
  Networking: "/circles/networking.jpg",
  "Paint and Sip": "/venues/museums.jpg",
  Hiking: "/circles/hiking.jpg",
  "Beach Day": "/circles/beachday.jpg",
  Yoga: "/venues/parks.jpg",
  "Art Gallery": "/venues/museums.jpg",
  "Comedy Night": "/venues/karaoke.jpg",
  Cinema: "/venues/cinemas.jpg",
  "Sports Viewing": "/venues/stadiums.jpg",
  Concert: "/circles/concert.jpg",
  Karaoke: "/venues/karaoke.jpg",
  Bowling: "/venues/bowling.jpg",
  "Pool Party": "/venues/hotels.jpg",
  Clubbing: "/venues/clubs.jpg",
  Party: "/circles/party.jpg",
  "Owambe": "/circles/party.jpg",
  "Afrobeats Night": "/circles/concert.jpg",
  "Brunch": "/venues/restaurants-2.jpg",
  "Rooftop Party": "/venues/rooftops.jpg",
  "Live Music": "/circles/concert.jpg",
  "Open Mic": "/venues/karaoke.jpg",
  "Tech Meetup": "/circles/networking.jpg",
  "Fitness": "/venues/gyms.jpg",
  "Road Trip": "/circles/hiking.jpg",
  "Birthday": "/circles/party.jpg",
  "Detty December": "/circles/party.jpg",
  "Volunteering": "/circles/networking.jpg",
  "Camping": "/circles/hiking.jpg",
  "Sightseeing": "/venues/museums.jpg",
  "Street Food": "/venues/restaurants-2.jpg",
  "Jogging": "/venues/parks.jpg",
  "Workshop": "/circles/networking.jpg",
  "Seminar": "/circles/networking.jpg",
  "Conference": "/venues/museums.jpg",
  "Career Fair": "/circles/networking.jpg",
  "Mentorship": "/circles/networking.jpg",
  "Business Meetup": "/circles/networking.jpg",
  "Startup / Pitch Night": "/circles/networking.jpg",
  "Study Abroad": "/circles/networking.jpg",
  "Skill Training": "/circles/networking.jpg",
  "Coding / Tech Class": "/circles/networking.jpg",
  "Language Exchange": "/circles/networking.jpg",
  "Masterclass": "/circles/networking.jpg",
  "Mental Health Talk": "/venues/parks.jpg",
  "Charity Event": "/circles/networking.jpg",
  "Alumni Meetup": "/circles/party.jpg",
  "Faith Gathering": "/venues/museums.jpg",
  "Singles Meetup": "/circles/party.jpg",
  "Market / Trade Fair": "/venues/restaurants-2.jpg",
  "Product Launch": "/circles/party.jpg",
  "Food Tasting": "/venues/restaurants.jpg",
  "Cooking Class": "/venues/restaurants.jpg",
  "Wine / Cocktail Night": "/venues/rooftops.jpg",
  "Street Food Tour": "/venues/restaurants-2.jpg",
  "Suya Night": "/venues/restaurants-2.jpg",
  "Coffee Meetup": "/venues/restaurants.jpg",
  "Gym Session": "/venues/gyms.jpg",
  "Meditation": "/venues/parks.jpg",
  "Wellness Walk": "/venues/parks.jpg",
  "Sports": "/venues/stadiums.jpg",
  "Cycling": "/venues/parks.jpg",
  "Adventure Park": "/venues/parks.jpg",
  "Photography Walk": "/venues/parks.jpg",
  "Art Exhibition": "/venues/museums.jpg",
  "Movie Screening": "/venues/cinemas.jpg",
  "Theatre / Drama": "/venues/museums.jpg",
  "Fashion Meetup": "/circles/party.jpg",
  "Fashion Pop-up": "/circles/party.jpg",
  "Listening Party": "/circles/concert.jpg",
  "After-Party": "/circles/party.jpg",
  "Cultural Day": "/circles/party.jpg",
  "Family Fun Day": "/venues/parks.jpg",
  "Kids Event": "/venues/parks.jpg",
  "Game Tournament": "/circles/gamenight.jpg",
  "Outdoor": "/venues/parks.jpg",
  "Entertainment": "/venues/cinemas.jpg",
  "Community & Social": "/circles/networking.jpg",
  "Festival": "/circles/concert.jpg",
  "Boat Cruise": "/venues/beaches.jpg",
  "Day Party": "/circles/party.jpg",
  "Silent Disco": "/venues/clubs-2.jpg",
  "Trivia Night": "/circles/gamenight.jpg",
  "Wine Tasting": "/venues/restaurants-2.jpg",
  "Spa Day": "/venues/hotels.jpg",
  "Go-Karting": "/venues/stadiums.jpg",
  "Fashion Show": "/venues/museums.jpg",
  "Baby Shower": "/circles/party.jpg",
  "Graduation Party": "/circles/party.jpg",
};

export function categoryPhoto(category: string | null | undefined): string {
  return PHOTOS[category ?? ""] ?? "/circles/networking.jpg";
}
