// Shared constants for LinkUpNaija

export const NIGERIAN_STATES = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT - Abuja",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
] as const;

export type NigerianState = (typeof NIGERIAN_STATES)[number];

// Ordered to lead with family/friendship/connection-oriented gatherings;
// nightlife sits at the end. This order flows through every category list and
// filter across the site.
export const EVENT_CATEGORIES = [
  "Family Hangout",
  "Friend Reunion",
  "Picnic",
  "Book Club",
  "Game Night",
  "Dinner",
  "Networking",
  "Board Games",
  "Paint and Sip",
  "Hiking",
  "Beach Day",
  "Yoga",
  "Food Festival",
  "Art Gallery",
  "Comedy Night",
  "Cinema",
  "Sports Viewing",
  "Concert",
  "Karaoke",
  "Bowling",
  "Pool Party",
  "Clubbing",
  "Party",
  "Owambe",
  "Afrobeats Night",
  "Brunch",
  "Rooftop Party",
  "Live Music",
  "Open Mic",
  "Tech Meetup",
  "Fitness",
  "Road Trip",
  "Birthday",
  "Detty December",
  "Volunteering",
  "Camping",
  "Sightseeing",
  "Street Food",
  "Jogging",
  "Workshop",
  "Seminar",
  "Conference",
  "Career Fair",
  "Mentorship",
  "Business Meetup",
  "Startup / Pitch Night",
  "Study Abroad",
  "Skill Training",
  "Coding / Tech Class",
  "Language Exchange",
  "Masterclass",
  "Mental Health Talk",
  "Charity Event",
  "Alumni Meetup",
  "Faith Gathering",
  "Singles Meetup",
  "Market / Trade Fair",
  "Product Launch",
  "Food Tasting",
  "Cooking Class",
  "Wine / Cocktail Night",
  "Street Food Tour",
  "Suya Night",
  "Coffee Meetup",
  "Gym Session",
  "Meditation",
  "Wellness Walk",
  "Sports",
  "Cycling",
  "Adventure Park",
  "Photography Walk",
  "Art Exhibition",
  "Movie Screening",
  "Theatre / Drama",
  "Fashion Meetup",
  "Fashion Pop-up",
  "Listening Party",
  "After-Party",
  "Cultural Day",
  "Family Fun Day",
  "Kids Event",
  "Game Tournament",
  "Outdoor",
  "Entertainment",
  "Community & Social",
  "Festival",
  "Boat Cruise",
  "Day Party",
  "Silent Disco",
  "Trivia Night",
  "Wine Tasting",
  "Spa Day",
  "Go-Karting",
  "Fashion Show",
  "Baby Shower",
  "Graduation Party",
] as const;

export type EventCategory = (typeof EVENT_CATEGORIES)[number];

// ---------------------------------------------------------------------------
// Interests — what users pick during onboarding (Substack/Tinder style).
// Grouped for a scannable chip picker. Each interest maps loosely to event
// categories so we can recommend events that match.
// ---------------------------------------------------------------------------
export interface InterestGroup {
  title: string;
  interests: { label: string; emoji: string }[];
}

export const INTEREST_GROUPS: InterestGroup[] = [
  {
    title: "🎉 Nightlife & Social",
    interests: [
      { label: "Parties", emoji: "🎉" },
      { label: "Clubbing", emoji: "🪩" },
      { label: "Karaoke", emoji: "🎤" },
      { label: "Comedy", emoji: "😂" },
      { label: "Concerts", emoji: "🎫" },
      { label: "Pool Parties", emoji: "🏊" },
    ],
  },
  {
    title: "🍽️ Food & Drink",
    interests: [
      { label: "Dining Out", emoji: "🍽️" },
      { label: "Food Festivals", emoji: "🥘" },
      { label: "Street Food", emoji: "🍢" },
      { label: "Paint & Sip", emoji: "🎨" },
      { label: "Coffee & Chill", emoji: "☕" },
      { label: "Cooking", emoji: "👩‍🍳" },
    ],
  },
  {
    title: "🎨 Arts & Culture",
    interests: [
      { label: "Live Music", emoji: "🎶" },
      { label: "Art Galleries", emoji: "🖼️" },
      { label: "Cinema", emoji: "🎬" },
      { label: "Photography", emoji: "📷" },
      { label: "Fashion", emoji: "👗" },
    ],
  },
  {
    title: "🏃 Active & Outdoors",
    interests: [
      { label: "Hiking", emoji: "🥾" },
      { label: "Beach Days", emoji: "🏖️" },
      { label: "Yoga", emoji: "🧘" },
      { label: "Fitness", emoji: "💪" },
      { label: "Jogging", emoji: "🏃" },
      { label: "Sightseeing", emoji: "🗺️" },
      { label: "Camping", emoji: "⛺" },
      { label: "Football", emoji: "⚽" },
      { label: "Sports Viewing", emoji: "📺" },
    ],
  },
  {
    title: "🧠 Learning & Growth",
    interests: [
      { label: "Book Clubs", emoji: "📚" },
      { label: "Networking", emoji: "🤝" },
      { label: "Tech & Startups", emoji: "💻" },
      { label: "Public Speaking", emoji: "🎙️" },
      { label: "Faith", emoji: "🙏" },
    ],
  },
  {
    title: "🎮 Play & Chill",
    interests: [
      { label: "Board Games", emoji: "♟️" },
      { label: "Video Games", emoji: "🎮" },
      { label: "Movie Nights", emoji: "🍿" },
      { label: "Picnics", emoji: "🧺" },
      { label: "Family Hangouts", emoji: "👨‍👩‍👧‍👦" },
      { label: "Friend Reunions", emoji: "🤗" },
    ],
  },
];

// Flat list of every valid interest label (for validation/lookup).
export const ALL_INTERESTS: string[] = INTEREST_GROUPS.flatMap((g) =>
  g.interests.map((i) => i.label)
);

// Minimum interests we ask a user to pick during onboarding.
export const MIN_INTERESTS = 3;

// Maps an interest label → the event categories that satisfy it. Powers the
// "Picked for you" personalised feed. Interests without a category match
// (e.g. Coffee & Chill, Fashion) simply don't surface events yet.
export const INTEREST_TO_CATEGORIES: Record<string, EventCategory[]> = {
  Parties: ["Party"],
  Clubbing: ["Clubbing"],
  Karaoke: ["Karaoke"],
  Comedy: ["Comedy Night"],
  Concerts: ["Concert"],
  "Pool Parties": ["Pool Party"],
  "Dining Out": ["Dinner"],
  "Food Festivals": ["Food Festival", "Street Food"],
  "Street Food": ["Street Food", "Food Festival"],
  "Paint & Sip": ["Paint and Sip"],
  Cooking: ["Food Festival", "Dinner"],
  "Live Music": ["Concert"],
  "Art Galleries": ["Art Gallery"],
  Cinema: ["Cinema"],
  Hiking: ["Hiking", "Camping"],
  Jogging: ["Jogging", "Fitness"],
  Sightseeing: ["Sightseeing", "Road Trip"],
  Camping: ["Camping", "Hiking"],
  "Beach Days": ["Beach Day"],
  Yoga: ["Yoga"],
  Fitness: ["Yoga", "Hiking", "Jogging"],
  Football: ["Sports Viewing"],
  "Sports Viewing": ["Sports Viewing"],
  "Book Clubs": ["Book Club"],
  Networking: ["Networking"],
  "Tech & Startups": ["Networking"],
  "Board Games": ["Board Games", "Game Night"],
  "Video Games": ["Game Night"],
  "Movie Nights": ["Cinema"],
  Picnics: ["Picnic"],
  "Family Hangouts": ["Family Hangout"],
  "Friend Reunions": ["Friend Reunion"],
};

// Union of event categories that match a user's interests.
export function categoriesForInterests(interests: string[]): EventCategory[] {
  const set = new Set<EventCategory>();
  for (const i of interests) {
    for (const c of INTEREST_TO_CATEGORIES[i] ?? []) set.add(c);
  }
  return Array.from(set);
}

// Each category gets its own badge styling (Tailwind classes).
export const CATEGORY_STYLES: Record<
  EventCategory,
  { badge: string; emoji: string }
> = {
  "Family Hangout": { badge: "bg-orange-100 text-orange-700", emoji: "👨‍👩‍👧‍👦" },
  "Friend Reunion": { badge: "bg-teal-100 text-teal-700", emoji: "🤗" },
  Clubbing: { badge: "bg-purple-100 text-purple-700", emoji: "🪩" },
  Party: { badge: "bg-pink-100 text-pink-700", emoji: "🎉" },
  Picnic: { badge: "bg-green-100 text-green-700", emoji: "🧺" },
  "Book Club": { badge: "bg-amber-100 text-amber-700", emoji: "📚" },
  Dinner: { badge: "bg-rose-100 text-rose-700", emoji: "🍽️" },
  "Game Night": { badge: "bg-blue-100 text-blue-700", emoji: "🎮" },
  Cinema: { badge: "bg-indigo-100 text-indigo-700", emoji: "🎬" },
  "Sports Viewing": { badge: "bg-emerald-100 text-emerald-700", emoji: "📺" },
  Hiking: { badge: "bg-lime-100 text-lime-700", emoji: "🥾" },
  "Beach Day": { badge: "bg-cyan-100 text-cyan-700", emoji: "🏖️" },
  "Comedy Night": { badge: "bg-yellow-100 text-yellow-700", emoji: "😂" },
  Concert: { badge: "bg-fuchsia-100 text-fuchsia-700", emoji: "🎶" },
  "Art Gallery": { badge: "bg-rose-100 text-rose-700", emoji: "🖼️" },
  Bowling: { badge: "bg-blue-100 text-blue-700", emoji: "🎳" },
  Karaoke: { badge: "bg-purple-100 text-purple-700", emoji: "🎤" },
  "Pool Party": { badge: "bg-sky-100 text-sky-700", emoji: "🏊" },
  Yoga: { badge: "bg-teal-100 text-teal-700", emoji: "🧘" },
  "Board Games": { badge: "bg-orange-100 text-orange-700", emoji: "🎲" },
  "Food Festival": { badge: "bg-red-100 text-red-700", emoji: "🍢" },
  "Paint and Sip": { badge: "bg-pink-100 text-pink-700", emoji: "🎨" },
  Networking: { badge: "bg-slate-100 text-slate-700", emoji: "🤝" },
  "Owambe": { badge: "bg-amber-100 text-amber-800", emoji: "💃" },
  "Afrobeats Night": { badge: "bg-fuchsia-100 text-fuchsia-700", emoji: "🎶" },
  "Brunch": { badge: "bg-orange-100 text-orange-700", emoji: "🥞" },
  "Rooftop Party": { badge: "bg-sky-100 text-sky-700", emoji: "🌆" },
  "Live Music": { badge: "bg-rose-100 text-rose-700", emoji: "🎸" },
  "Open Mic": { badge: "bg-violet-100 text-violet-700", emoji: "🎙️" },
  "Tech Meetup": { badge: "bg-slate-100 text-slate-700", emoji: "💻" },
  "Fitness": { badge: "bg-lime-100 text-lime-700", emoji: "🏋️" },
  "Road Trip": { badge: "bg-cyan-100 text-cyan-700", emoji: "🚐" },
  "Birthday": { badge: "bg-pink-100 text-pink-700", emoji: "🎂" },
  "Detty December": { badge: "bg-red-100 text-red-700", emoji: "🎊" },
  "Volunteering": { badge: "bg-emerald-100 text-emerald-700", emoji: "🤲" },
  "Camping": { badge: "bg-lime-100 text-lime-700", emoji: "⛺" },
  "Sightseeing": { badge: "bg-sky-100 text-sky-700", emoji: "🗺️" },
  "Street Food": { badge: "bg-orange-100 text-orange-700", emoji: "🍢" },
  "Jogging": { badge: "bg-lime-100 text-lime-700", emoji: "🏃" },
  "Workshop": { badge: "bg-gray-100 text-gray-700", emoji: "🛠️" },
  "Seminar": { badge: "bg-gray-100 text-gray-700", emoji: "🎓" },
  "Conference": { badge: "bg-gray-100 text-gray-700", emoji: "🏛️" },
  "Career Fair": { badge: "bg-gray-100 text-gray-700", emoji: "💼" },
  "Mentorship": { badge: "bg-gray-100 text-gray-700", emoji: "🤲" },
  "Business Meetup": { badge: "bg-gray-100 text-gray-700", emoji: "📈" },
  "Startup / Pitch Night": { badge: "bg-gray-100 text-gray-700", emoji: "🚀" },
  "Study Abroad": { badge: "bg-gray-100 text-gray-700", emoji: "✈️" },
  "Skill Training": { badge: "bg-gray-100 text-gray-700", emoji: "🧠" },
  "Coding / Tech Class": { badge: "bg-gray-100 text-gray-700", emoji: "💻" },
  "Language Exchange": { badge: "bg-gray-100 text-gray-700", emoji: "🗣️" },
  "Masterclass": { badge: "bg-gray-100 text-gray-700", emoji: "🎯" },
  "Mental Health Talk": { badge: "bg-gray-100 text-gray-700", emoji: "💚" },
  "Charity Event": { badge: "bg-gray-100 text-gray-700", emoji: "🎗️" },
  "Alumni Meetup": { badge: "bg-gray-100 text-gray-700", emoji: "🎓" },
  "Faith Gathering": { badge: "bg-gray-100 text-gray-700", emoji: "🙏" },
  "Singles Meetup": { badge: "bg-gray-100 text-gray-700", emoji: "💘" },
  "Market / Trade Fair": { badge: "bg-gray-100 text-gray-700", emoji: "🛍️" },
  "Product Launch": { badge: "bg-gray-100 text-gray-700", emoji: "🎉" },
  "Food Tasting": { badge: "bg-gray-100 text-gray-700", emoji: "🍽️" },
  "Cooking Class": { badge: "bg-gray-100 text-gray-700", emoji: "👩‍🍳" },
  "Wine / Cocktail Night": { badge: "bg-gray-100 text-gray-700", emoji: "🍸" },
  "Street Food Tour": { badge: "bg-gray-100 text-gray-700", emoji: "🍢" },
  "Suya Night": { badge: "bg-gray-100 text-gray-700", emoji: "🔥" },
  "Coffee Meetup": { badge: "bg-gray-100 text-gray-700", emoji: "☕" },
  "Gym Session": { badge: "bg-gray-100 text-gray-700", emoji: "💪" },
  "Meditation": { badge: "bg-gray-100 text-gray-700", emoji: "🧘" },
  "Wellness Walk": { badge: "bg-gray-100 text-gray-700", emoji: "🚶" },
  "Sports": { badge: "bg-gray-100 text-gray-700", emoji: "⚽" },
  "Cycling": { badge: "bg-gray-100 text-gray-700", emoji: "🚴" },
  "Adventure Park": { badge: "bg-gray-100 text-gray-700", emoji: "🎢" },
  "Photography Walk": { badge: "bg-gray-100 text-gray-700", emoji: "📷" },
  "Art Exhibition": { badge: "bg-gray-100 text-gray-700", emoji: "🖼️" },
  "Movie Screening": { badge: "bg-gray-100 text-gray-700", emoji: "🎬" },
  "Theatre / Drama": { badge: "bg-gray-100 text-gray-700", emoji: "🎭" },
  "Fashion Meetup": { badge: "bg-gray-100 text-gray-700", emoji: "👗" },
  "Fashion Pop-up": { badge: "bg-gray-100 text-gray-700", emoji: "🛒" },
  "Listening Party": { badge: "bg-gray-100 text-gray-700", emoji: "🎧" },
  "After-Party": { badge: "bg-gray-100 text-gray-700", emoji: "🌃" },
  "Cultural Day": { badge: "bg-gray-100 text-gray-700", emoji: "🇳🇬" },
  "Family Fun Day": { badge: "bg-gray-100 text-gray-700", emoji: "🎈" },
  "Kids Event": { badge: "bg-gray-100 text-gray-700", emoji: "🧸" },
  "Game Tournament": { badge: "bg-gray-100 text-gray-700", emoji: "🏆" },
  "Outdoor": { badge: "bg-gray-100 text-gray-700", emoji: "🌤️" },
  "Entertainment": { badge: "bg-gray-100 text-gray-700", emoji: "🎭" },
  "Community & Social": { badge: "bg-gray-100 text-gray-700", emoji: "🤝" },
  "Festival": { badge: "bg-gray-100 text-gray-700", emoji: "🎪" },
  "Boat Cruise": { badge: "bg-sky-100 text-sky-700", emoji: "🛥️" },
  "Day Party": { badge: "bg-yellow-100 text-yellow-700", emoji: "☀️" },
  "Silent Disco": { badge: "bg-violet-100 text-violet-700", emoji: "🎧" },
  "Trivia Night": { badge: "bg-indigo-100 text-indigo-700", emoji: "🧠" },
  "Wine Tasting": { badge: "bg-rose-100 text-rose-700", emoji: "🍷" },
  "Spa Day": { badge: "bg-cyan-100 text-cyan-700", emoji: "💆" },
  "Go-Karting": { badge: "bg-red-100 text-red-700", emoji: "🏎️" },
  "Fashion Show": { badge: "bg-fuchsia-100 text-fuchsia-700", emoji: "👗" },
  "Baby Shower": { badge: "bg-pink-100 text-pink-700", emoji: "🍼" },
  "Graduation Party": { badge: "bg-amber-100 text-amber-700", emoji: "🎓" },
};

export function categoryStyle(category: string) {
  return (
    CATEGORY_STYLES[category as EventCategory] ?? {
      badge: "bg-gray-100 text-gray-700",
      emoji: "✨",
    }
  );
}

// Gradient placeholder (Tailwind classes) used when an event has no cover image.
export const CATEGORY_GRADIENTS: Record<EventCategory, string> = {
  "Family Hangout": "from-orange-400 to-amber-500",
  "Friend Reunion": "from-teal-400 to-cyan-500",
  Clubbing: "from-purple-500 to-indigo-600",
  Party: "from-pink-500 to-rose-500",
  Picnic: "from-green-500 to-emerald-600",
  "Book Club": "from-amber-500 to-orange-600",
  Dinner: "from-rose-500 to-red-600",
  "Game Night": "from-blue-500 to-cyan-600",
  Cinema: "from-indigo-500 to-purple-600",
  "Sports Viewing": "from-emerald-500 to-green-600",
  Hiking: "from-lime-500 to-green-600",
  "Beach Day": "from-cyan-500 to-blue-500",
  "Comedy Night": "from-yellow-400 to-amber-500",
  Concert: "from-fuchsia-500 to-pink-600",
  "Art Gallery": "from-rose-500 to-pink-600",
  Bowling: "from-blue-500 to-indigo-600",
  Karaoke: "from-purple-500 to-fuchsia-600",
  "Pool Party": "from-sky-400 to-cyan-500",
  Yoga: "from-teal-500 to-emerald-600",
  "Board Games": "from-orange-500 to-amber-600",
  "Food Festival": "from-red-500 to-orange-600",
  "Paint and Sip": "from-pink-500 to-rose-500",
  Networking: "from-slate-500 to-gray-600",
  "Owambe": "from-amber-400 to-orange-500",
  "Afrobeats Night": "from-fuchsia-500 to-purple-600",
  "Brunch": "from-orange-300 to-amber-400",
  "Rooftop Party": "from-sky-500 to-indigo-500",
  "Live Music": "from-rose-500 to-pink-600",
  "Open Mic": "from-violet-500 to-purple-600",
  "Tech Meetup": "from-slate-500 to-gray-700",
  "Fitness": "from-lime-500 to-green-600",
  "Road Trip": "from-cyan-500 to-teal-600",
  "Birthday": "from-pink-400 to-rose-500",
  "Detty December": "from-red-500 to-rose-600",
  "Volunteering": "from-emerald-500 to-green-600",
  "Camping": "from-lime-500 to-green-600",
  "Sightseeing": "from-sky-500 to-cyan-600",
  "Street Food": "from-orange-500 to-amber-600",
  "Jogging": "from-lime-500 to-emerald-600",
  "Workshop": "from-slate-500 to-gray-600",
  "Seminar": "from-blue-500 to-indigo-600",
  "Conference": "from-indigo-500 to-blue-700",
  "Career Fair": "from-cyan-600 to-blue-700",
  "Mentorship": "from-teal-500 to-cyan-600",
  "Business Meetup": "from-slate-600 to-blue-700",
  "Startup / Pitch Night": "from-violet-500 to-fuchsia-600",
  "Study Abroad": "from-sky-500 to-blue-600",
  "Skill Training": "from-emerald-500 to-teal-600",
  "Coding / Tech Class": "from-slate-700 to-indigo-700",
  "Language Exchange": "from-amber-500 to-orange-600",
  "Masterclass": "from-purple-600 to-indigo-700",
  "Mental Health Talk": "from-green-500 to-emerald-600",
  "Charity Event": "from-rose-500 to-pink-600",
  "Alumni Meetup": "from-blue-600 to-indigo-700",
  "Faith Gathering": "from-amber-400 to-yellow-600",
  "Singles Meetup": "from-pink-500 to-rose-600",
  "Market / Trade Fair": "from-orange-500 to-amber-600",
  "Product Launch": "from-fuchsia-500 to-purple-600",
  "Food Tasting": "from-rose-500 to-red-600",
  "Cooking Class": "from-orange-500 to-red-600",
  "Wine / Cocktail Night": "from-rose-600 to-pink-700",
  "Street Food Tour": "from-amber-500 to-orange-600",
  "Suya Night": "from-red-500 to-orange-600",
  "Coffee Meetup": "from-amber-700 to-yellow-800",
  "Gym Session": "from-emerald-500 to-green-700",
  "Meditation": "from-teal-400 to-cyan-600",
  "Wellness Walk": "from-green-400 to-emerald-600",
  "Sports": "from-green-600 to-emerald-700",
  "Cycling": "from-cyan-500 to-teal-600",
  "Adventure Park": "from-orange-500 to-red-600",
  "Photography Walk": "from-slate-500 to-gray-700",
  "Art Exhibition": "from-purple-500 to-violet-700",
  "Movie Screening": "from-indigo-600 to-purple-700",
  "Theatre / Drama": "from-red-600 to-rose-700",
  "Fashion Meetup": "from-pink-500 to-fuchsia-600",
  "Fashion Pop-up": "from-rose-500 to-pink-600",
  "Listening Party": "from-purple-600 to-indigo-700",
  "After-Party": "from-purple-700 to-slate-900",
  "Cultural Day": "from-green-600 to-emerald-700",
  "Family Fun Day": "from-sky-400 to-blue-500",
  "Kids Event": "from-yellow-400 to-orange-500",
  "Game Tournament": "from-amber-500 to-yellow-600",
  "Outdoor": "from-sky-500 to-cyan-600",
  "Entertainment": "from-violet-500 to-indigo-600",
  "Community & Social": "from-teal-500 to-emerald-600",
  "Festival": "from-orange-500 to-red-600",
  "Boat Cruise": "from-sky-500 to-blue-600",
  "Day Party": "from-yellow-400 to-amber-500",
  "Silent Disco": "from-violet-500 to-purple-600",
  "Trivia Night": "from-indigo-500 to-blue-600",
  "Wine Tasting": "from-rose-500 to-red-600",
  "Spa Day": "from-cyan-400 to-teal-500",
  "Go-Karting": "from-red-500 to-orange-600",
  "Fashion Show": "from-fuchsia-500 to-pink-600",
  "Baby Shower": "from-pink-400 to-rose-500",
  "Graduation Party": "from-amber-500 to-yellow-600",
};

export function categoryGradient(category: string) {
  return (
    CATEGORY_GRADIENTS[category as EventCategory] ?? "from-brand-400 to-brand-700"
  );
}
